### ISSUE TITLE
Error during processing | Resource not found

### ISSUE THREAD

**Issue by bristauss** [jlengstorf/image-processing#1]
I've tried to follow the tutorial as close as possible and I understand this is still new so different issues can pop up.

When I run the build in Netlify, I get the following error (seems to repeat for each image):

```
11:27:57 AM: Error during processing { Error: 5 NOT_FOUND: Resource not found (resource=netlify-gatsby-images_image-processing).
11:27:57 AM:     at Object.exports.createStatusError (/opt/build/repo/node_modules/grpc/src/common.js:91:15)
11:27:57 AM:     at Object.onReceiveStatus (/opt/build/repo/node_modules/grpc/src/client_interceptors.js:1209:28)
11:27:57 AM:     at InterceptingListener._callNext (/opt/build/repo/node_modules/grpc/src/client_interceptors.js:568:42)
11:27:57 AM:     at InterceptingListener.onReceiveStatus (/opt/build/repo/node_modules/grpc/src/client_interceptors.js:618:8)
11:27:57 AM:     at callback (/opt/build/repo/node_modules/grpc/src/client_interceptors.js:847:24)
11:27:57 AM:   code: 5,
11:27:57 AM:   metadata: Metadata { _internal_repr: {}, flags: 0 },
11:27:57 AM:   details:
11:27:57 AM:    'Resource not found (resource=netlify-gatsby-images_image-processing).',
11:27:57 AM:   note:
11:27:57 AM:    'Exception occurred in retry method that was not classified as transient' }
```
My set up is a little different as I'm sourcing images from a few different api's using source plugins (i.e. Instagram).

Any idea what the cause is?

Also, if this is not the best place for getting help, let me know and I can close this and submit where appropriate. Thanks!

**Comment by jlengstorf** [comment]
hey, @bristauss — are your logs public? could you link to them here? I can pass this along to the team and see if we can figure out why it's happening

**Comment by bristauss** [comment]
Hi @jlengstorf, sorry for the delay in getting back on here.

I've attempted to figure this out myself but I am still facing issues. After meticulously going back through the tutorial video, the above error no longer appears, however, now I see a new error.

First off as a side note, I took the nuclear option of completely deleting the site from Netlify, re-creating the site (as it was prior to adding gatsby-parallel-runner), and re-deployed. The site built and deployed great just as expected.

Starting from scratch I then went back through the video and implemented `gatsby-parallel-runner` as explained in the video. Two things happened:

1. The `Generating image thumbnails` time didn't change (still took over 300 seconds—so something is still off).
2. I get a new error: `Failed to upload file: submit-contact-form` (I posted about this error to the Netlify community [here](https://community.netlify.com/t/deploy-failed-due-to-upload-file/6456/5?u=bristizzy) and [here](https://community.netlify.com/t/deploy-failed-due-to-upload-file/6456/8?u=bristizzy) awhile back thinking it was due to Gatsby Cloud). The worst part about this error is I can't reverse it. When I remove the `gatsby-parallel-runner` build command the error continues to persist.

The logs aren't public, but I'm happy to share whatever is needed to help solve the issue. Thanks!

**Comment by jlengstorf** [comment]
@bristauss if you don't mind putting the logs into a gist or something that's really helpful for debugging

the error you're listing doesn't seem related to the images, but I'm happy to try and help spot the issue!

**Comment by bristauss** [comment]
@jlengstorf, after spending time creating the gist for you I found my issue upon further inspecting the logs. I added the `gatsby-parallel-runner` command in the Netlify dashboard, not in my netlify.toml file :flushed:

After updating that, the both issues went away. I now have builds of 2m 30s instead of 6m 26s!

Thanks for being so responsive to us newbies. I really enjoy your teaching style!

**Comment by jlengstorf** [comment]
great! thanks so much for reporting back, and thanks for watching/reading!
